package com.ac.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table book
 *
 * @mbg.generated do_not_delete_during_merge Tue Oct 19 09:49:36 CST 2021
 */
public class Book {
    /**
     * Database Column Remarks:
     *   图书ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_id
     *
     * @mbg.generated Tue Oct 19 09:49:36 CST 2021
     */
    private Integer bookId;

    /**
     * Database Column Remarks:
     *   作者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.author_name
     *
     * @mbg.generated Tue Oct 19 09:49:36 CST 2021
     */
    private String authorName;

    /**
     * Database Column Remarks:
     *   出版社
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.publisher_name
     *
     * @mbg.generated Tue Oct 19 09:49:36 CST 2021
     */
    private String publisherName;

    /**
     * Database Column Remarks:
     *   书名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_name
     *
     * @mbg.generated Tue Oct 19 09:49:36 CST 2021
     */
    private String bookName;

    /**
     * Database Column Remarks:
     *   库存
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.quantity
     *
     * @mbg.generated Tue Oct 19 09:49:36 CST 2021
     */
    private Integer quantity;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.create_date_time
     *
     * @mbg.generated Tue Oct 19 09:49:36 CST 2021
     */
    private Date createDateTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.update_date_time
     *
     * @mbg.generated Tue Oct 19 09:49:36 CST 2021
     */
    private Date updateDateTime;

    /**
     * Database Column Remarks:
     *   删除flag
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.delete_flag
     *
     * @mbg.generated Tue Oct 19 09:49:36 CST 2021
     */
    private Boolean deleteFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_id
     *
     * @return the value of book.book_id
     *
     * @mbg.generated Tue Oct 19 09:49:36 CST 2021
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_id
     *
     * @param bookId the value for book.book_id
     *
     * @mbg.generated Tue Oct 19 09:49:36 CST 2021
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.author_name
     *
     * @return the value of book.author_name
     *
     * @mbg.generated Tue Oct 19 09:49:36 CST 2021
     */
    public String getAuthorName() {
        return authorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.author_name
     *
     * @param authorName the value for book.author_name
     *
     * @mbg.generated Tue Oct 19 09:49:36 CST 2021
     */
    public void setAuthorName(String authorName) {
        this.authorName = authorName == null ? null : authorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.publisher_name
     *
     * @return the value of book.publisher_name
     *
     * @mbg.generated Tue Oct 19 09:49:36 CST 2021
     */
    public String getPublisherName() {
        return publisherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.publisher_name
     *
     * @param publisherName the value for book.publisher_name
     *
     * @mbg.generated Tue Oct 19 09:49:36 CST 2021
     */
    public void setPublisherName(String publisherName) {
        this.publisherName = publisherName == null ? null : publisherName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_name
     *
     * @return the value of book.book_name
     *
     * @mbg.generated Tue Oct 19 09:49:36 CST 2021
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_name
     *
     * @param bookName the value for book.book_name
     *
     * @mbg.generated Tue Oct 19 09:49:36 CST 2021
     */
    public void setBookName(String bookName) {
        this.bookName = bookName == null ? null : bookName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.quantity
     *
     * @return the value of book.quantity
     *
     * @mbg.generated Tue Oct 19 09:49:36 CST 2021
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.quantity
     *
     * @param quantity the value for book.quantity
     *
     * @mbg.generated Tue Oct 19 09:49:36 CST 2021
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.create_date_time
     *
     * @return the value of book.create_date_time
     *
     * @mbg.generated Tue Oct 19 09:49:36 CST 2021
     */
    public Date getCreateDateTime() {
        return createDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.create_date_time
     *
     * @param createDateTime the value for book.create_date_time
     *
     * @mbg.generated Tue Oct 19 09:49:36 CST 2021
     */
    public void setCreateDateTime(Date createDateTime) {
        this.createDateTime = createDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.update_date_time
     *
     * @return the value of book.update_date_time
     *
     * @mbg.generated Tue Oct 19 09:49:36 CST 2021
     */
    public Date getUpdateDateTime() {
        return updateDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.update_date_time
     *
     * @param updateDateTime the value for book.update_date_time
     *
     * @mbg.generated Tue Oct 19 09:49:36 CST 2021
     */
    public void setUpdateDateTime(Date updateDateTime) {
        this.updateDateTime = updateDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.delete_flag
     *
     * @return the value of book.delete_flag
     *
     * @mbg.generated Tue Oct 19 09:49:36 CST 2021
     */
    public Boolean getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.delete_flag
     *
     * @param deleteFlag the value for book.delete_flag
     *
     * @mbg.generated Tue Oct 19 09:49:36 CST 2021
     */
    public void setDeleteFlag(Boolean deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Tue Oct 19 09:49:36 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", bookId=").append(bookId);
        sb.append(", authorName=").append(authorName);
        sb.append(", publisherName=").append(publisherName);
        sb.append(", bookName=").append(bookName);
        sb.append(", quantity=").append(quantity);
        sb.append(", createDateTime=").append(createDateTime);
        sb.append(", updateDateTime=").append(updateDateTime);
        sb.append(", deleteFlag=").append(deleteFlag);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Tue Oct 19 09:49:36 CST 2021
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Book other = (Book) that;
        return (this.getBookId() == null ? other.getBookId() == null : this.getBookId().equals(other.getBookId()))
            && (this.getAuthorName() == null ? other.getAuthorName() == null : this.getAuthorName().equals(other.getAuthorName()))
            && (this.getPublisherName() == null ? other.getPublisherName() == null : this.getPublisherName().equals(other.getPublisherName()))
            && (this.getBookName() == null ? other.getBookName() == null : this.getBookName().equals(other.getBookName()))
            && (this.getQuantity() == null ? other.getQuantity() == null : this.getQuantity().equals(other.getQuantity()))
            && (this.getCreateDateTime() == null ? other.getCreateDateTime() == null : this.getCreateDateTime().equals(other.getCreateDateTime()))
            && (this.getUpdateDateTime() == null ? other.getUpdateDateTime() == null : this.getUpdateDateTime().equals(other.getUpdateDateTime()))
            && (this.getDeleteFlag() == null ? other.getDeleteFlag() == null : this.getDeleteFlag().equals(other.getDeleteFlag()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Tue Oct 19 09:49:36 CST 2021
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getBookId() == null) ? 0 : getBookId().hashCode());
        result = prime * result + ((getAuthorName() == null) ? 0 : getAuthorName().hashCode());
        result = prime * result + ((getPublisherName() == null) ? 0 : getPublisherName().hashCode());
        result = prime * result + ((getBookName() == null) ? 0 : getBookName().hashCode());
        result = prime * result + ((getQuantity() == null) ? 0 : getQuantity().hashCode());
        result = prime * result + ((getCreateDateTime() == null) ? 0 : getCreateDateTime().hashCode());
        result = prime * result + ((getUpdateDateTime() == null) ? 0 : getUpdateDateTime().hashCode());
        result = prime * result + ((getDeleteFlag() == null) ? 0 : getDeleteFlag().hashCode());
        return result;
    }
}