package com.ac.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table borrow_history
 *
 * @mbg.generated do_not_delete_during_merge Thu Oct 21 10:45:46 CST 2021
 */
public class BorrowHistory {
    /**
     * Database Column Remarks:
     *   履历ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_history.history_id
     *
     * @mbg.generated Thu Oct 21 10:45:46 CST 2021
     */
    private Integer historyId;

    /**
     * Database Column Remarks:
     *   用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_history.user_id
     *
     * @mbg.generated Thu Oct 21 10:45:46 CST 2021
     */
    private Integer userId;

    /**
     * Database Column Remarks:
     *   图书ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_history.book_id
     *
     * @mbg.generated Thu Oct 21 10:45:46 CST 2021
     */
    private Integer bookId;

    /**
     * Database Column Remarks:
     *   借阅日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_history.borrow_date
     *
     * @mbg.generated Thu Oct 21 10:45:46 CST 2021
     */
    private Date borrowDate;

    /**
     * Database Column Remarks:
     *   归还日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_history.return_date
     *
     * @mbg.generated Thu Oct 21 10:45:46 CST 2021
     */
    private Date returnDate;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_history.create_date_time
     *
     * @mbg.generated Thu Oct 21 10:45:46 CST 2021
     */
    private Date createDateTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_history.update_date_time
     *
     * @mbg.generated Thu Oct 21 10:45:46 CST 2021
     */
    private Date updateDateTime;

    /**
     * Database Column Remarks:
     *   删除flag
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_history.delete_flag
     *
     * @mbg.generated Thu Oct 21 10:45:46 CST 2021
     */
    private Boolean deleteFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_history.history_id
     *
     * @return the value of borrow_history.history_id
     *
     * @mbg.generated Thu Oct 21 10:45:46 CST 2021
     */
    public Integer getHistoryId() {
        return historyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_history.history_id
     *
     * @param historyId the value for borrow_history.history_id
     *
     * @mbg.generated Thu Oct 21 10:45:46 CST 2021
     */
    public void setHistoryId(Integer historyId) {
        this.historyId = historyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_history.user_id
     *
     * @return the value of borrow_history.user_id
     *
     * @mbg.generated Thu Oct 21 10:45:46 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_history.user_id
     *
     * @param userId the value for borrow_history.user_id
     *
     * @mbg.generated Thu Oct 21 10:45:46 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_history.book_id
     *
     * @return the value of borrow_history.book_id
     *
     * @mbg.generated Thu Oct 21 10:45:46 CST 2021
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_history.book_id
     *
     * @param bookId the value for borrow_history.book_id
     *
     * @mbg.generated Thu Oct 21 10:45:46 CST 2021
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_history.borrow_date
     *
     * @return the value of borrow_history.borrow_date
     *
     * @mbg.generated Thu Oct 21 10:45:46 CST 2021
     */
    public Date getBorrowDate() {
        return borrowDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_history.borrow_date
     *
     * @param borrowDate the value for borrow_history.borrow_date
     *
     * @mbg.generated Thu Oct 21 10:45:46 CST 2021
     */
    public void setBorrowDate(Date borrowDate) {
        this.borrowDate = borrowDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_history.return_date
     *
     * @return the value of borrow_history.return_date
     *
     * @mbg.generated Thu Oct 21 10:45:46 CST 2021
     */
    public Date getReturnDate() {
        return returnDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_history.return_date
     *
     * @param returnDate the value for borrow_history.return_date
     *
     * @mbg.generated Thu Oct 21 10:45:46 CST 2021
     */
    public void setReturnDate(Date returnDate) {
        this.returnDate = returnDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_history.create_date_time
     *
     * @return the value of borrow_history.create_date_time
     *
     * @mbg.generated Thu Oct 21 10:45:46 CST 2021
     */
    public Date getCreateDateTime() {
        return createDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_history.create_date_time
     *
     * @param createDateTime the value for borrow_history.create_date_time
     *
     * @mbg.generated Thu Oct 21 10:45:46 CST 2021
     */
    public void setCreateDateTime(Date createDateTime) {
        this.createDateTime = createDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_history.update_date_time
     *
     * @return the value of borrow_history.update_date_time
     *
     * @mbg.generated Thu Oct 21 10:45:46 CST 2021
     */
    public Date getUpdateDateTime() {
        return updateDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_history.update_date_time
     *
     * @param updateDateTime the value for borrow_history.update_date_time
     *
     * @mbg.generated Thu Oct 21 10:45:46 CST 2021
     */
    public void setUpdateDateTime(Date updateDateTime) {
        this.updateDateTime = updateDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_history.delete_flag
     *
     * @return the value of borrow_history.delete_flag
     *
     * @mbg.generated Thu Oct 21 10:45:46 CST 2021
     */
    public Boolean getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_history.delete_flag
     *
     * @param deleteFlag the value for borrow_history.delete_flag
     *
     * @mbg.generated Thu Oct 21 10:45:46 CST 2021
     */
    public void setDeleteFlag(Boolean deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_history
     *
     * @mbg.generated Thu Oct 21 10:45:46 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", historyId=").append(historyId);
        sb.append(", userId=").append(userId);
        sb.append(", bookId=").append(bookId);
        sb.append(", borrowDate=").append(borrowDate);
        sb.append(", returnDate=").append(returnDate);
        sb.append(", createDateTime=").append(createDateTime);
        sb.append(", updateDateTime=").append(updateDateTime);
        sb.append(", deleteFlag=").append(deleteFlag);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_history
     *
     * @mbg.generated Thu Oct 21 10:45:46 CST 2021
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BorrowHistory other = (BorrowHistory) that;
        return (this.getHistoryId() == null ? other.getHistoryId() == null : this.getHistoryId().equals(other.getHistoryId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getBookId() == null ? other.getBookId() == null : this.getBookId().equals(other.getBookId()))
            && (this.getBorrowDate() == null ? other.getBorrowDate() == null : this.getBorrowDate().equals(other.getBorrowDate()))
            && (this.getReturnDate() == null ? other.getReturnDate() == null : this.getReturnDate().equals(other.getReturnDate()))
            && (this.getCreateDateTime() == null ? other.getCreateDateTime() == null : this.getCreateDateTime().equals(other.getCreateDateTime()))
            && (this.getUpdateDateTime() == null ? other.getUpdateDateTime() == null : this.getUpdateDateTime().equals(other.getUpdateDateTime()))
            && (this.getDeleteFlag() == null ? other.getDeleteFlag() == null : this.getDeleteFlag().equals(other.getDeleteFlag()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_history
     *
     * @mbg.generated Thu Oct 21 10:45:46 CST 2021
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getHistoryId() == null) ? 0 : getHistoryId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getBookId() == null) ? 0 : getBookId().hashCode());
        result = prime * result + ((getBorrowDate() == null) ? 0 : getBorrowDate().hashCode());
        result = prime * result + ((getReturnDate() == null) ? 0 : getReturnDate().hashCode());
        result = prime * result + ((getCreateDateTime() == null) ? 0 : getCreateDateTime().hashCode());
        result = prime * result + ((getUpdateDateTime() == null) ? 0 : getUpdateDateTime().hashCode());
        result = prime * result + ((getDeleteFlag() == null) ? 0 : getDeleteFlag().hashCode());
        return result;
    }
}