package com.ac.mapper;

import com.ac.entity.BorrowHistory;
import com.ac.entity.BorrowHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BorrowHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_history
     *
     * @mbg.generated Thu Oct 21 10:45:46 CST 2021
     */
    long countByExample(BorrowHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_history
     *
     * @mbg.generated Thu Oct 21 10:45:46 CST 2021
     */
    int deleteByExample(BorrowHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_history
     *
     * @mbg.generated Thu Oct 21 10:45:46 CST 2021
     */
    int deleteByPrimaryKey(Integer historyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_history
     *
     * @mbg.generated Thu Oct 21 10:45:46 CST 2021
     */
    int insert(BorrowHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_history
     *
     * @mbg.generated Thu Oct 21 10:45:46 CST 2021
     */
    int insertSelective(BorrowHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_history
     *
     * @mbg.generated Thu Oct 21 10:45:46 CST 2021
     */
    List<BorrowHistory> selectByExample(BorrowHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_history
     *
     * @mbg.generated Thu Oct 21 10:45:46 CST 2021
     */
    BorrowHistory selectByPrimaryKey(Integer historyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_history
     *
     * @mbg.generated Thu Oct 21 10:45:46 CST 2021
     */
    int updateByExampleSelective(@Param("record") BorrowHistory record, @Param("example") BorrowHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_history
     *
     * @mbg.generated Thu Oct 21 10:45:46 CST 2021
     */
    int updateByExample(@Param("record") BorrowHistory record, @Param("example") BorrowHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_history
     *
     * @mbg.generated Thu Oct 21 10:45:46 CST 2021
     */
    int updateByPrimaryKeySelective(BorrowHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table borrow_history
     *
     * @mbg.generated Thu Oct 21 10:45:46 CST 2021
     */
    int updateByPrimaryKey(BorrowHistory record);
}